# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Project SAMMI
email: sammi-list@lists.mitre.org
description: > # this means to ignore newlines until "baseurl:"
  SAMMI is focused on a data driven system model of the opioid epidemic that will take into account drug sources, 
  abuse pathways, substance costs, response program costs, the care landscape, and patient outcomes, 
  with the ultimate goal of reducing the harm from substance abuse in Massachusetts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://projectsammi.github.io" # the base hostname & protocol for your site
github_username:  projectsammi

# Build settings
markdown: kramdown
